export const languages = [
    // Official South African Languages
    { code: 'english', name: 'English' },
    { code: 'afrikaans', name: 'Afrikaans' },
    { code: 'isi_ndebele', name: 'isiNdebele' },
    { code: 'isi_xhosa', name: 'isiXhosa' },
    { code: 'isi_zulu', name: 'isiZulu' },
    { code: 'sesotho', name: 'Sesotho' },
    { code: 'setswana', name: 'Setswana' },
    { code: 'sepedi', name: 'Sepedi' },
    { code: 'si_swati', name: 'siSwati' },
    { code: 'tshivenda', name: 'Tshivenda' },
    { code: 'xitsonga', name: 'Xitsonga' },
    
    // Additional Popular Languages
    { code: 'arabic', name: 'Arabic' },
    { code: 'bengali', name: 'Bengali' },
    { code: 'bulgarian', name: 'Bulgarian' },
    { code: 'catalan', name: 'Catalan' },
    { code: 'croatian', name: 'Croatian' },
    { code: 'czech', name: 'Czech' },
    { code: 'danish', name: 'Danish' },
    { code: 'dutch', name: 'Dutch' },
    { code: 'estonian', name: 'Estonian' },
    { code: 'finnish', name: 'Finnish' },
    { code: 'french', name: 'French' },
    { code: 'german', name: 'German' },
    { code: 'greek', name: 'Greek' },
    { code: 'hebrew', name: 'Hebrew' },
    { code: 'hindi', name: 'Hindi' },
    { code: 'hungarian', name: 'Hungarian' },
    { code: 'icelandic', name: 'Icelandic' },
    { code: 'irish', name: 'Irish' },
    { code: 'italian', name: 'Italian' },
    { code: 'japanese', name: 'Japanese' },
    { code: 'korean', name: 'Korean' },
    { code: 'latvian', name: 'Latvian' },
    { code: 'lithuanian', name: 'Lithuanian' },
    { code: 'maltese', name: 'Maltese' },
    { code: 'mandarin', name: 'Mandarin Chinese' },
    { code: 'norwegian', name: 'Norwegian' },
    { code: 'polish', name: 'Polish' },
    { code: 'portuguese', name: 'Portuguese' },
    { code: 'romanian', name: 'Romanian' },
    { code: 'russian', name: 'Russian' },
    { code: 'slovak', name: 'Slovak' },
    { code: 'slovenian', name: 'Slovenian' },
    { code: 'spanish', name: 'Spanish' },
    { code: 'swedish', name: 'Swedish' },
    { code: 'turkish', name: 'Turkish' },
    { code: 'ukrainian', name: 'Ukrainian' },
    { code: 'vietnamese', name: 'Vietnamese' },
    { code: 'welsh', name: 'Welsh' }
];
